name: orchestrator-build
on:
  push:
    branches:
      - main
    paths:
      - services/orchestrator/**
      - packages/**
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/service-build
        with:
          service: orchestrator
          tag: "pharmaceutical-orchestrator:${{ github.sha }}-${{ github.run_attempt }}"
          access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
          repository_access_token: ${{ secrets.REPOSITORY_ACCESS_TOKEN }}